name: Terraform Auto Format

on:
  pull_request:

jobs:
  terraform-fmt:
    name: Auto Format Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Commit formatting changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "terraform-bot"
            git config user.email "terraform-bot@github.com"
            git add .
            git commit -m "chore(terraform): auto format"
            git push
          else
            echo "No formatting changes needed"
          fi
